### ISSUE TITLE
What is the data format for  Bi-RNN?

### ISSUE THREAD

**Issue by NourKhdour** [sheffieldnlp/deepQuest-py#5]
Hello,
i want to train QE using Bi-RNN architecture. According to this code, [the](
https://github.com/sheffieldnlp/deepQuest-py/blob/4af1b119fb13d9e322d6524107295d1405c2fe53/deepquestpy/data/birnn_sent_reader.py#L43) training data consists of src, mt, score, and t_pred. What is a t_pred file?

**Comment by amitgajbhiye** [comment]
The main branch of the code is the student BiRNN model, which considers the teacher model predictions (https://aclanthology.org/2021.findings-acl.452.pdf). "t_pred" are the teacher model predictions.

The "birnn" branch of the repo implements the original BiRNN (https://aclanthology.org/C18-1266.pdf) model. This model considers the input in the (source, target, score) format.
